#!/usr/bin/env Rscript

# =============================================================================
# build-book.R
# -----------------------------------------------------------------------------
# Generates the Quarto book under book/ from the author-edited Markdown files
# in cases/. That content is maintained in a separate repository
# (crimes-against-causality/cases) and lives here under cases/ — cloned
# there by CI, or by you locally. Override the location with the CASES_DIR
# environment variable.
#
# For each cases/NN-slug/case-file*.md it:
#   * reads the YAML front matter (number, title, detective, difficulty,
#     topics, fallacies, summary)
#   * splits the body into a CASE part (crime scene + exhibits + interrogation)
#     and a SOLUTION part (answers + what went wrong + background + sources)
#   * copies any referenced images into the book and rewrites the links
#   * writes book/cases/case-NN.qmd and book/solutions/solution-NN.qmd
#
# It also (re)generates:
#   * book/cases/overview.qmd        – sortable table of all cases
#   * book/solutions/index.qmd       – landing page for the solutions part
#   * book/references.qmd            – aggregated bibliography
#   * book/appendix-index.qmd        – tag index (topic / fallacy / difficulty)
#   * book/intro/detectives.qmd      – from cases/detectives.md
#   * book/intro/world.qmd           – from cases/lore.md
#   * book/_quarto.yml               – the book definition + chapter list
#
# Authors normally only ever touch the Markdown in cases/. To add a new
# case, drop a new NN-slug/ folder with a case-file*.md (front matter + the
# usual section headings) and re-run this script.
#
# Usage:  Rscript scripts/build-book.R
# =============================================================================

suppressPackageStartupMessages({
  library(yaml)
  library(stringr)
})

# ---- configuration (edit here to change book-level metadata) ----------------

BOOK <- list(
  title    = "Crimes Against Causality",
  subtitle = "An interactive mystery-solving book about flawed scientific evidence",
  authors  = c("Simon Munzert", "Dylan Thurgood"),
  site_url = "https://crimes-against-causality.github.io/",
  repo_url = "https://github.com/crimes-against-causality/crimes-against-causality.github.io",
  gallery_title = "The Rogues' Gallery",
  # difficulty code -> human label
  difficulty_labels = c("1" = "Easy", "2" = "Medium", "3" = "Hard")
)

# ---- paths ------------------------------------------------------------------

root        <- normalizePath(file.path(dirname(sub("--file=", "",
                 grep("--file=", commandArgs(FALSE), value = TRUE)[1])), ".."),
                 mustWork = FALSE)
if (is.na(root) || !nzchar(root)) root <- normalizePath(".")
cases_src   <- Sys.getenv("CASES_DIR", unset = file.path(root, "cases"))
book_dir    <- file.path(root, "book")
dir_cases   <- file.path(book_dir, "cases")
dir_solns   <- file.path(book_dir, "solutions")
dir_intro   <- file.path(book_dir, "intro")

for (d in c(book_dir, dir_cases, dir_solns, dir_intro,
            file.path(dir_cases, "assets"), file.path(dir_solns, "assets"))) {
  dir.create(d, showWarnings = FALSE, recursive = TRUE)
}

GENERATED_NOTE <- paste0(
  "<!-- DO NOT EDIT. Generated by scripts/build-book.R from the Markdown\n",
  "     in cases/. Edit the source case files and re-run the build. -->\n\n")

# ---- helpers ----------------------------------------------------------------

`%||%` <- function(a, b) if (is.null(a) || (length(a) == 1 && is.na(a))) b else a

# Write a character vector to disk as UTF-8, regardless of the session locale.
write_utf8 <- function(lines, path) {
  con <- file(path, open = "wb")
  on.exit(close(con))
  writeLines(enc2utf8(as.character(lines)), con, useBytes = TRUE)
}

# Strip the cosmetic inline HTML that some case files use in headings/text.
clean_inline_html <- function(x) {
  x <- str_replace_all(x, "<br\\s*/?>", " ")
  x <- str_replace_all(x, "</?span[^>]*>", "")
  str_squish(x)
}

# Read a case file and return list(meta = <yaml>, body = <character vector>).
read_case <- function(path) {
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  if (length(lines) == 0 || !str_detect(lines[1], "^---\\s*$")) {
    stop("Case file is missing YAML front matter: ", path)
  }
  close_idx <- which(str_detect(lines, "^---\\s*$"))[2]
  if (is.na(close_idx)) stop("Unterminated YAML front matter: ", path)
  meta <- yaml.load(paste(lines[2:(close_idx - 1)], collapse = "\n"))
  body <- lines[(close_idx + 1):length(lines)]
  # drop the leading H1 title line (we render the title from front matter)
  first_h1 <- which(str_detect(body, "^#\\s"))[1]
  if (!is.na(first_h1)) body <- body[-(1:first_h1)]
  # trim leading blank lines
  while (length(body) && !nzchar(str_trim(body[1]))) body <- body[-1]
  list(meta = meta, body = body)
}

# Index of heading lines whose (cleaned) text matches a regex, case-insensitive.
heading_matching <- function(body, pattern) {
  is_h    <- str_detect(body, "^#{1,6}\\s")
  cleaned <- clean_inline_html(str_replace(body, "^#{1,6}\\s*", ""))
  which(is_h & str_detect(cleaned, regex(pattern, ignore_case = TRUE)))
}

# Split a body into the case half and the solution half at the "Answers" heading.
split_case_solution <- function(body, slug) {
  ans <- heading_matching(body, "^answers?\\b")
  if (length(ans) == 0) {
    warning("No 'Answers' heading found in ", slug,
            " \u2014 treating whole file as the case.")
    return(list(case = body, solution = character(0)))
  }
  cut <- ans[1]
  list(case = body[seq_len(cut - 1)], solution = body[cut:length(body)])
}

# Copy referenced local images for one body part into <dest>/assets and rewrite
# the links. Returns the rewritten body.
relocate_images <- function(body, src_dir, dest_dir, prefix) {
  img_re <- "!\\[[^]]*\\]\\(([^)]+)\\)"
  for (i in seq_along(body)) {
    m <- str_match_all(body[i], img_re)[[1]]
    if (nrow(m) == 0) next
    for (j in seq_len(nrow(m))) {
      path <- m[j, 2]
      if (str_detect(path, "^https?://")) next
      src <- file.path(src_dir, path)
      if (!file.exists(src)) {
        warning("Missing image referenced in ", basename(src_dir), ": ", path)
        next
      }
      newname <- paste0(prefix, "-", basename(path))
      file.copy(src, file.path(dest_dir, "assets", newname), overwrite = TRUE)
      body[i] <- str_replace(body[i], stringr::fixed(path),
                             file.path("assets", newname))
    }
  }
  body
}

# Clean heading lines so the TOC / anchors are tidy (keeps body text as-is).
tidy_headings <- function(body) {
  is_h <- str_detect(body, "^#{1,6}\\s")
  body[is_h] <- vapply(body[is_h], function(h) {
    hashes <- str_extract(h, "^#{1,6}")
    paste(hashes, clean_inline_html(str_replace(h, "^#{1,6}\\s*", "")))
  }, character(1))
  body
}

# Fold "## Exhibit N: ..." headings into the crime-scene flow. Exhibits are part
# of the scene, not separate sections, so turn the heading into a bold label.
fold_exhibits <- function(body) {
  is_h <- str_detect(body, "^#{1,6}\\s")
  txt  <- str_replace(body, "^#{1,6}\\s*", "")
  hit  <- is_h & str_detect(txt, regex("^\\**exhibit\\b", ignore_case = TRUE))
  body[hit] <- paste0("**", str_trim(str_replace_all(txt[hit], "\\*+", "")), "**")
  body
}

difficulty_label <- function(d) {
  lbl <- BOOK$difficulty_labels[as.character(d)]
  if (is.na(lbl)) as.character(d) else unname(lbl)
}
difficulty_dots <- function(d) {
  d <- suppressWarnings(as.integer(d)); if (is.na(d)) return("")
  paste0(strrep("\u25cf", d), strrep("\u25cb", max(0, 3 - d)))
}

as_vec <- function(x) if (is.null(x)) character(0) else unlist(x, use.names = FALSE)

pad2 <- function(n) sprintf("%02d", as.integer(n))

# ---- discover cases ---------------------------------------------------------

case_dirs <- list.dirs(cases_src, recursive = FALSE, full.names = TRUE)
case_dirs <- case_dirs[str_detect(basename(case_dirs), "^[0-9]+-")]
case_dirs <- case_dirs[order(as.integer(str_extract(basename(case_dirs), "^[0-9]+")))]

cases <- list()
for (cd in case_dirs) {
  cf <- list.files(cd, pattern = "^case-file.*\\.md$", full.names = TRUE)
  if (length(cf) == 0) {
    warning("No case-file*.md in ", cd, " \u2014 skipping.")
    next
  }
  cf <- cf[1]
  parsed <- read_case(cf)
  meta   <- parsed$meta
  num    <- as.integer(meta$number %||% str_extract(basename(cd), "^[0-9]+"))
  n2     <- pad2(num)

  parts    <- split_case_solution(parsed$body, meta$slug %||% basename(cd))
  case_body <- fold_exhibits(tidy_headings(relocate_images(parts$case, cd, dir_cases, n2)))
  soln_body <- tidy_headings(relocate_images(parts$solution, cd, dir_solns, n2))

  cases[[length(cases) + 1]] <- list(
    number = num, n2 = n2, dir = cd,
    title = meta$title %||% basename(cd),
    detective = meta$detective %||% "",
    author = meta$author %||% "",
    difficulty = meta$difficulty %||% NA,
    topics = as_vec(meta$topics),
    fallacies = as_vec(meta$fallacies),
    summary = meta$summary %||% "",
    case_body = case_body, soln_body = soln_body
  )
}

if (length(cases) == 0) stop("No cases found under ", cases_src)
message("Found ", length(cases), " case(s).")

# ---- write per-case and per-solution chapters -------------------------------

badge_line <- function(cs) {
  paste0("**Detective:** ", cs$detective,
         "  \u00b7  **Difficulty:** ", difficulty_label(cs$difficulty),
         " ", difficulty_dots(cs$difficulty))
}
tag_line <- function(cs) {
  paste0("**Topics:** ", paste(cs$topics, collapse = ", "),
         "  \u00b7  **Fallacies:** ", paste(cs$fallacies, collapse = ", "))
}

for (cs in cases) {
  case_qmd <- file.path(dir_cases, paste0("case-", cs$n2, ".qmd"))
  soln_rel <- file.path("..", "solutions", paste0("solution-", cs$n2, ".qmd"))
  write_utf8(c(
    "---",
    paste0("title: \"", cs$n2, " \u00b7 ", cs$title, "\""),
    "---",
    "",
    paste0(GENERATED_NOTE),
    cs$case_body,
    "",
    "------------------------------------------------------------------------",
    "",
    paste0("[**\u2192 Reveal the solution**](", soln_rel, "){.solution-link}"),
    ""
  ), case_qmd)

  soln_qmd <- file.path(dir_solns, paste0("solution-", cs$n2, ".qmd"))
  case_rel <- file.path("..", "cases", paste0("case-", cs$n2, ".qmd"))
  write_utf8(c(
    "---",
    paste0("title: \"", cs$n2, " \u00b7 ", cs$title, "\""),
    "---",
    "",
    paste0(GENERATED_NOTE),
    paste0("[\u2190 Back to the case](", case_rel, "){.back-link}"),
    "",
    "------------------------------------------------------------------------",
    "",
    cs$soln_body,
    ""
  ), soln_qmd)
}

# ---- overview table ---------------------------------------------------------

ov <- c(
  "---", "title: \"Overview\"", "---", "",
  GENERATED_NOTE,
  "Six crimes against causality await. Each one is a real-looking study, chart,",
  "or algorithm with a fatal flaw buried inside it. Read the crime scene, work",
  "through the interrogation, and form your own verdict before you reveal the",
  "solution.",
  "",
  "Cases are investigated by one of two detectives \u2014 see [The Detectives](../intro/detectives.qmd).",
  "Difficulty runs from \u25cf (Easy) to \u25cf\u25cf\u25cf (Hard).",
  "",
  "| # | Case | Detective | Difficulty | Topics |",
  "|---|------|-----------|:----------:|--------|"
)
for (cs in cases) {
  link <- paste0("[**", cs$title, "**](case-", cs$n2, ".qmd)<br><span class='case-blurb'>",
                 cs$summary, "</span>")
  ov <- c(ov, paste(
    "|", cs$n2,
    "|", link,
    "|", cs$detective,
    "|", paste0(difficulty_dots(cs$difficulty), "<br>", difficulty_label(cs$difficulty)),
    "|", paste(cs$topics, collapse = ", "), "|"))
}
write_utf8(ov, file.path(dir_cases, "overview.qmd"))

# ---- fallacy -> cases mapping (used by the solutions overview and the gallery)

slug <- function(x) {
  x <- tolower(x)
  x <- gsub("[^a-z0-9]+", "-", x)
  gsub("(^-|-$)", "", x)
}

fallacy_cases <- list()
for (cs in cases) for (f in cs$fallacies) {
  fallacy_cases[[f]] <- c(fallacy_cases[[f]], cs$n2)
}

# ---- solutions landing page -------------------------------------------------

soln_idx <- c(
  "---", "title: \"Overview\"", "---", "",
  GENERATED_NOTE,
  "Spoilers ahead. Each solution lays out the answers to the interrogation,",
  "explains what went wrong, gives the background, and points to further reading.",
  "Every solution links back to its case.",
  "",
  paste0("Jump to a solution: ",
    paste(vapply(cases, function(cs)
      paste0("[", cs$n2, "](solution-", cs$n2, ".qmd)"), character(1)),
      collapse = " \u00b7 ")),
  "",
  "## Fallacies at a glance",
  "",
  paste0("Each case turns on one or more *crimes against causality*. Follow a ",
         "suspect to the [", BOOK$gallery_title,
         "](../compendium/index.qmd) for a plain-language explanation."),
  "",
  "| Fallacy | Cases |",
  "|---------|-------|"
)
for (f in sort(names(fallacy_cases))) {
  links <- vapply(fallacy_cases[[f]], function(n)
    paste0("[", n, "](../cases/case-", n, ".qmd)"), character(1))
  flink <- paste0("[", f, "](../compendium/", slug(f), ".qmd)")
  soln_idx <- c(soln_idx, paste("|", flink, "|", paste(links, collapse = ", "), "|"))
}
write_utf8(soln_idx, file.path(dir_solns, "index.qmd"))

# ---- aggregated bibliography ------------------------------------------------

collect_sources <- function(cs) {
  b <- cs$soln_body
  h <- heading_matching(b, "^sources?\\b|^further reading\\b|^references?\\b")
  if (length(h) == 0) return(character(0))
  start <- h[1] + 1
  nxt <- which(str_detect(b, "^#{1,6}\\s"))
  nxt <- nxt[nxt > h[1]]
  end <- if (length(nxt)) nxt[1] - 1 else length(b)
  src <- b[start:end]
  src <- src[str_detect(src, "^\\s*-\\s")]
  str_trim(str_replace(src, "^\\s*-\\s*", ""))
}
all_src <- unique(unlist(lapply(cases, collect_sources)))
all_src <- all_src[nzchar(all_src)]
all_src <- all_src[order(tolower(all_src))]
write_utf8(c(
  "---", "title: \"References & Further Reading\"", "---", "",
  GENERATED_NOTE,
  "Sources cited across all cases, collected here for convenience. Each case",
  "also lists its own sources at the end of its solution.",
  "",
  if (length(all_src)) paste0("- ", all_src) else "_No sources found._"
), file.path(book_dir, "references.qmd"))

# ---- tag index --------------------------------------------------------------

build_index_block <- function(field, label) {
  tagmap <- list()
  for (cs in cases) {
    for (t in cs[[field]]) {
      tagmap[[t]] <- c(tagmap[[t]], cs$n2)
    }
  }
  if (length(tagmap) == 0) return(character(0))
  out <- paste0("## ", label, "\n")
  for (t in sort(names(tagmap))) {
    ns <- tagmap[[t]]
    links <- vapply(ns, function(n)
      paste0("[", n, "](cases/case-", n, ".qmd)"), character(1))
    out <- c(out, paste0("**", t, "** \u2014 ", paste(links, collapse = ", "), "\n"))
  }
  c(out, "")
}
idx <- c(
  "---", "title: \"Index\"", "---", "",
  GENERATED_NOTE,
  "Find cases by what they are about and by the kind of reasoning error they",
  "expose.",
  "",
  build_index_block("topics", "By topic"),
  build_index_block("fallacies", "By fallacy"),
  build_index_block_difficulty <- {
    tagmap <- list()
    for (cs in cases) {
      lbl <- difficulty_label(cs$difficulty)
      tagmap[[lbl]] <- c(tagmap[[lbl]], cs$n2)
    }
    out <- "## By difficulty\n"
    for (lbl in c("Easy", "Medium", "Hard")) {
      if (is.null(tagmap[[lbl]])) next
      links <- vapply(tagmap[[lbl]], function(n)
        paste0("[", n, "](cases/case-", n, ".qmd)"), character(1))
      out <- c(out, paste0("**", lbl, "** \u2014 ", paste(links, collapse = ", "), "\n"))
    }
    out
  }
)
write_utf8(idx, file.path(book_dir, "appendix-index.qmd"))

# ---- intro pages from cases/*.md -------------------------------------

transform_simple_md <- function(src, dest, title, drop_from = NULL) {
  if (!file.exists(src)) {
    warning("Source not found, skipping: ", src); return(invisible())
  }
  lines <- readLines(src, warn = FALSE, encoding = "UTF-8")
  first_h1 <- which(str_detect(lines, "^#\\s"))[1]
  if (!is.na(first_h1)) lines <- lines[-(1:first_h1)]
  if (!is.null(drop_from)) {
    d <- heading_matching(lines, drop_from)
    if (length(d)) lines <- lines[seq_len(d[1] - 1)]
  }
  lines <- tidy_headings(lines)
  write_utf8(c("---", paste0("title: \"", title, "\""), "---", "",
               GENERATED_NOTE, lines), dest)
}
transform_simple_md(file.path(cases_src, "detectives.md"),
                    file.path(dir_intro, "detectives.qmd"),
                    "The Detectives", drop_from = "^case assignments")
transform_simple_md(file.path(cases_src, "lore.md"),
                    file.path(dir_intro, "world.qmd"),
                    "The World of Harland")

# ---- the rogues' gallery (fallacy compendium) -------------------------------

# Parse cases/fallacies.md into ordered (name, body) entries, one per "## " head.
parse_fallacies <- function(path) {
  if (!file.exists(path)) {
    warning("fallacies.md not found: ", path); return(list())
  }
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  h <- which(str_detect(lines, "^##\\s"))
  entries <- list()
  for (i in seq_along(h)) {
    start <- h[i]
    end   <- if (i < length(h)) h[i + 1] - 1 else length(lines)
    name  <- str_trim(str_replace(lines[start], "^##\\s*", ""))
    body  <- lines[(start + 1):end]
    while (length(body) && !nzchar(str_trim(body[1]))) body <- body[-1]
    while (length(body) && !nzchar(str_trim(body[length(body)]))) body <- body[-length(body)]
    entries[[length(entries) + 1]] <- list(name = name, body = body)
  }
  entries
}

title_by_n2 <- setNames(
  vapply(cases, function(cc) cc$title, character(1)),
  vapply(cases, function(cc) cc$n2, character(1)))

dir_comp <- file.path(book_dir, "compendium")
dir.create(dir_comp, showWarnings = FALSE, recursive = TRUE)

fallacy_entries <- parse_fallacies(file.path(cases_src, "fallacies.md"))
gallery_files <- character(0)

# Gallery landing page: the lineup, with a suspect -> cases table.
gintro <- c(
  "---", paste0("title: \"", BOOK$gallery_title, "\""), "---", "",
  GENERATED_NOTE,
  "Every case in this book is the work of a recurring suspect: a way of reading",
  "evidence that turns honest data into a false conclusion. This is the lineup.",
  "",
  "Each suspect below gets a short, plain-language file — no technical training",
  "required, only the willingness to ask one more question before believing a",
  "number.",
  "",
  "| Suspect | Caught in |",
  "|---------|-----------|"
)
for (e in fallacy_entries) {
  ns <- fallacy_cases[[e$name]]
  caught <- if (is.null(ns)) "—" else
    paste(vapply(ns, function(n) paste0("[", n, "](../cases/case-", n, ".qmd)"),
                 character(1)), collapse = ", ")
  gintro <- c(gintro, paste0("| [", e$name, "](", slug(e$name), ".qmd) | ", caught, " |"))
}
write_utf8(gintro, file.path(dir_comp, "index.qmd"))
gallery_files <- c(gallery_files, "compendium/index.qmd")

# One page per suspect.
for (e in fallacy_entries) {
  ns <- fallacy_cases[[e$name]]
  caught <- if (is.null(ns)) character(0) else c("",
    paste0("**Caught in:** ",
      paste(vapply(ns, function(n)
        paste0("[", n, " · ", title_by_n2[[n]], "](../cases/case-", n, ".qmd)"),
        character(1)), collapse = ", ")))
  pg <- c("---", paste0("title: \"", e$name, "\""), "---", "",
          GENERATED_NOTE, e$body, caught, "")
  write_utf8(pg, file.path(dir_comp, paste0(slug(e$name), ".qmd")))
  gallery_files <- c(gallery_files, paste0("compendium/", slug(e$name), ".qmd"))
}

# Sanity check: every fallacy tagged on a case should have an explanation.
missing_def <- setdiff(names(fallacy_cases),
                       vapply(fallacy_entries, function(e) e$name, character(1)))
if (length(missing_def)) {
  warning("Fallacies tagged in cases but missing from fallacies.md: ",
          paste(missing_def, collapse = "; "))
}

# ---- author colour-coding for the sidebar / table of contents ---------------

# Each distinct author gets a colour slot (a, b, c, ...) in book-author order.
# The actual colours are defined per theme as --author-a, --author-b, ... in
# theme.scss (light) and theme-dark.scss (noir), so they stay legible in both.
case_authors <- unique(Filter(nzchar, vapply(cases, function(c) c$author, character(1))))
author_order <- c(intersect(BOOK$authors, case_authors),
                  setdiff(case_authors, BOOK$authors))
author_slot  <- setNames(letters[seq_along(author_order)], author_order)

acss <- c(
  "/* Generated by scripts/build-book.R. Colour-codes the sidebar/ToC entries",
  "   by author. Colours: --author-a, --author-b, ... (defined per theme). */")
for (cs in cases) {
  if (!nzchar(cs$author)) next
  slot <- unname(author_slot[cs$author])
  if (is.na(slot)) next
  acss <- c(acss, paste0(
    "#quarto-sidebar a[href$=\"case-", cs$n2, ".html\"], ",
    "#quarto-sidebar a[href$=\"solution-", cs$n2, ".html\"] ",
    "{ color: var(--author-", slot, ") !important; }"))
}
write_utf8(acss, file.path(book_dir, "author-colors.css"))

# ---- _quarto.yml ------------------------------------------------------------

yml <- c(
  "# DO NOT EDIT. Generated by scripts/build-book.R.",
  "# Edit scripts/build-book.R (the BOOK list) to change book-level settings.",
  "project:",
  "  type: book",
  "  output-dir: _book",
  "",
  "book:",
  paste0("  title: \"", BOOK$title, "\""),
  paste0("  subtitle: \"", BOOK$subtitle, "\""),
  "  author:",
  paste0("    - \"", BOOK$authors, "\""),
  paste0("  site-url: \"", BOOK$site_url, "\""),
  paste0("  repo-url: \"", BOOK$repo_url, "\""),
  "  favicon: favicon.svg",
  "  search: true",
  "  page-navigation: true",
  "  chapters:",
  "    - index.qmd",
  "    - part: \"Introduction\"",
  "      chapters:",
  "        - intro/how-to-read.qmd",
  "        - intro/world.qmd",
  "        - intro/detectives.qmd",
  "    - part: \"The Cases\"",
  "      chapters:",
  "        - cases/overview.qmd"
)
yml <- c(yml, vapply(cases, function(cs)
  paste0("        - cases/case-", cs$n2, ".qmd"), character(1)))
yml <- c(yml,
  "    - part: \"The Solutions\"",
  "      chapters:",
  "        - solutions/index.qmd")
yml <- c(yml, vapply(cases, function(cs)
  paste0("        - solutions/solution-", cs$n2, ".qmd"), character(1)))
yml <- c(yml,
  paste0("    - part: \"", BOOK$gallery_title, "\""),
  "      chapters:")
yml <- c(yml, paste0("        - ", gallery_files))
yml <- c(yml,
  "  appendices:",
  "    - references.qmd",
  "    - appendix-index.qmd",
  "",
  "format:",
  "  html:",
  "    theme:",
  "      dark:",              # listed first -> noir is the default appearance
  "        - darkly",
  "        - theme-common.scss",
  "        - theme-dark.scss",
  "      light:",
  "        - cosmo",
  "        - theme-common.scss",
  "        - theme.scss",
  "    include-in-header: fonts-header.html",
  "    css: author-colors.css",
  "    toc: true",
  "    number-sections: false",
  "    fig-cap-location: top",
  "")
write_utf8(yml, file.path(book_dir, "_quarto.yml"))

message("Done. Wrote book/ for ", length(cases), " case(s).")
message("Render with:  quarto render book   (or: make preview)")
