#!/usr/bin/env Rscript

# =============================================================================
# build-book.R
# -----------------------------------------------------------------------------
# Generates the Quarto book under book/ from the author-edited Markdown files
# in case-studies/.
#
# For each case-studies/NN-slug/case-file*.md it:
#   * reads the YAML front matter (number, title, detective, difficulty,
#     topics, fallacies, summary)
#   * splits the body into a CASE part (crime scene + exhibits + interrogation)
#     and a SOLUTION part (answers + what went wrong + background + sources)
#   * copies any referenced images into the book and rewrites the links
#   * writes book/cases/case-NN.qmd and book/solutions/solution-NN.qmd
#
# It also (re)generates:
#   * book/cases/overview.qmd        – sortable table of all cases
#   * book/solutions/index.qmd       – landing page for the solutions part
#   * book/references.qmd            – aggregated bibliography
#   * book/appendix-index.qmd        – tag index (topic / fallacy / difficulty)
#   * book/intro/detectives.qmd      – from case-studies/detectives.md
#   * book/intro/world.qmd           – from case-studies/lore.md
#   * book/_quarto.yml               – the book definition + chapter list
#
# Authors normally only ever touch the Markdown in case-studies/. To add a new
# case, drop a new NN-slug/ folder with a case-file*.md (front matter + the
# usual section headings) and re-run this script.
#
# Usage:  Rscript scripts/build-book.R
# =============================================================================

suppressPackageStartupMessages({
  library(yaml)
  library(stringr)
})

# ---- configuration (edit here to change book-level metadata) ----------------

BOOK <- list(
  title    = "Crimes Against Causality",
  subtitle = "An interactive mystery-solving book about flawed scientific evidence",
  authors  = c("Simon Munzert", "Dylan Thurgood"),
  site_url = "https://crimes-against-causality.github.io/",
  repo_url = "https://github.com/crimes-against-causality/crimes-against-causality.github.io",
  # difficulty code -> human label
  difficulty_labels = c("1" = "Easy", "2" = "Medium", "3" = "Hard")
)

# ---- paths ------------------------------------------------------------------

root        <- normalizePath(file.path(dirname(sub("--file=", "",
                 grep("--file=", commandArgs(FALSE), value = TRUE)[1])), ".."),
                 mustWork = FALSE)
if (is.na(root) || !nzchar(root)) root <- normalizePath(".")
cases_src   <- file.path(root, "case-studies")
book_dir    <- file.path(root, "book")
dir_cases   <- file.path(book_dir, "cases")
dir_solns   <- file.path(book_dir, "solutions")
dir_intro   <- file.path(book_dir, "intro")

for (d in c(book_dir, dir_cases, dir_solns, dir_intro,
            file.path(dir_cases, "assets"), file.path(dir_solns, "assets"))) {
  dir.create(d, showWarnings = FALSE, recursive = TRUE)
}

GENERATED_NOTE <- paste0(
  "<!-- DO NOT EDIT. Generated by scripts/build-book.R from the Markdown\n",
  "     in case-studies/. Edit the source case files and re-run the build. -->\n\n")

# ---- helpers ----------------------------------------------------------------

`%||%` <- function(a, b) if (is.null(a) || (length(a) == 1 && is.na(a))) b else a

# Write a character vector to disk as UTF-8, regardless of the session locale.
write_utf8 <- function(lines, path) {
  con <- file(path, open = "wb")
  on.exit(close(con))
  writeLines(enc2utf8(as.character(lines)), con, useBytes = TRUE)
}

# Strip the cosmetic inline HTML that some case files use in headings/text.
clean_inline_html <- function(x) {
  x <- str_replace_all(x, "<br\\s*/?>", " ")
  x <- str_replace_all(x, "</?span[^>]*>", "")
  str_squish(x)
}

# Read a case file and return list(meta = <yaml>, body = <character vector>).
read_case <- function(path) {
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  if (length(lines) == 0 || !str_detect(lines[1], "^---\\s*$")) {
    stop("Case file is missing YAML front matter: ", path)
  }
  close_idx <- which(str_detect(lines, "^---\\s*$"))[2]
  if (is.na(close_idx)) stop("Unterminated YAML front matter: ", path)
  meta <- yaml.load(paste(lines[2:(close_idx - 1)], collapse = "\n"))
  body <- lines[(close_idx + 1):length(lines)]
  # drop the leading H1 title line (we render the title from front matter)
  first_h1 <- which(str_detect(body, "^#\\s"))[1]
  if (!is.na(first_h1)) body <- body[-(1:first_h1)]
  # trim leading blank lines
  while (length(body) && !nzchar(str_trim(body[1]))) body <- body[-1]
  list(meta = meta, body = body)
}

# Index of heading lines whose (cleaned) text matches a regex, case-insensitive.
heading_matching <- function(body, pattern) {
  is_h    <- str_detect(body, "^#{1,6}\\s")
  cleaned <- clean_inline_html(str_replace(body, "^#{1,6}\\s*", ""))
  which(is_h & str_detect(cleaned, regex(pattern, ignore_case = TRUE)))
}

# Split a body into the case half and the solution half at the "Answers" heading.
split_case_solution <- function(body, slug) {
  ans <- heading_matching(body, "^answers?\\b")
  if (length(ans) == 0) {
    warning("No 'Answers' heading found in ", slug,
            " \u2014 treating whole file as the case.")
    return(list(case = body, solution = character(0)))
  }
  cut <- ans[1]
  list(case = body[seq_len(cut - 1)], solution = body[cut:length(body)])
}

# Copy referenced local images for one body part into <dest>/assets and rewrite
# the links. Returns the rewritten body.
relocate_images <- function(body, src_dir, dest_dir, prefix) {
  img_re <- "!\\[[^]]*\\]\\(([^)]+)\\)"
  for (i in seq_along(body)) {
    m <- str_match_all(body[i], img_re)[[1]]
    if (nrow(m) == 0) next
    for (j in seq_len(nrow(m))) {
      path <- m[j, 2]
      if (str_detect(path, "^https?://")) next
      src <- file.path(src_dir, path)
      if (!file.exists(src)) {
        warning("Missing image referenced in ", basename(src_dir), ": ", path)
        next
      }
      newname <- paste0(prefix, "-", basename(path))
      file.copy(src, file.path(dest_dir, "assets", newname), overwrite = TRUE)
      body[i] <- str_replace(body[i], stringr::fixed(path),
                             file.path("assets", newname))
    }
  }
  body
}

# Clean heading lines so the TOC / anchors are tidy (keeps body text as-is).
tidy_headings <- function(body) {
  is_h <- str_detect(body, "^#{1,6}\\s")
  body[is_h] <- vapply(body[is_h], function(h) {
    hashes <- str_extract(h, "^#{1,6}")
    paste(hashes, clean_inline_html(str_replace(h, "^#{1,6}\\s*", "")))
  }, character(1))
  body
}

difficulty_label <- function(d) {
  lbl <- BOOK$difficulty_labels[as.character(d)]
  if (is.na(lbl)) as.character(d) else unname(lbl)
}
difficulty_dots <- function(d) {
  d <- suppressWarnings(as.integer(d)); if (is.na(d)) return("")
  paste0(strrep("\u25cf", d), strrep("\u25cb", max(0, 3 - d)))
}

as_vec <- function(x) if (is.null(x)) character(0) else unlist(x, use.names = FALSE)

pad2 <- function(n) sprintf("%02d", as.integer(n))

# ---- discover cases ---------------------------------------------------------

case_dirs <- list.dirs(cases_src, recursive = FALSE, full.names = TRUE)
case_dirs <- case_dirs[str_detect(basename(case_dirs), "^[0-9]+-")]
case_dirs <- case_dirs[order(as.integer(str_extract(basename(case_dirs), "^[0-9]+")))]

cases <- list()
for (cd in case_dirs) {
  cf <- list.files(cd, pattern = "^case-file.*\\.md$", full.names = TRUE)
  if (length(cf) == 0) {
    warning("No case-file*.md in ", cd, " \u2014 skipping.")
    next
  }
  cf <- cf[1]
  parsed <- read_case(cf)
  meta   <- parsed$meta
  num    <- as.integer(meta$number %||% str_extract(basename(cd), "^[0-9]+"))
  n2     <- pad2(num)

  parts    <- split_case_solution(parsed$body, meta$slug %||% basename(cd))
  case_body <- tidy_headings(relocate_images(parts$case, cd, dir_cases, n2))
  soln_body <- tidy_headings(relocate_images(parts$solution, cd, dir_solns, n2))

  cases[[length(cases) + 1]] <- list(
    number = num, n2 = n2, dir = cd,
    title = meta$title %||% basename(cd),
    detective = meta$detective %||% "",
    difficulty = meta$difficulty %||% NA,
    topics = as_vec(meta$topics),
    fallacies = as_vec(meta$fallacies),
    summary = meta$summary %||% "",
    case_body = case_body, soln_body = soln_body
  )
}

if (length(cases) == 0) stop("No cases found under ", cases_src)
message("Found ", length(cases), " case(s).")

# ---- write per-case and per-solution chapters -------------------------------

badge_line <- function(cs) {
  paste0("**Detective:** ", cs$detective,
         "  \u00b7  **Difficulty:** ", difficulty_label(cs$difficulty),
         " ", difficulty_dots(cs$difficulty))
}
tag_line <- function(cs) {
  paste0("**Topics:** ", paste(cs$topics, collapse = ", "),
         "  \u00b7  **Fallacies:** ", paste(cs$fallacies, collapse = ", "))
}

for (cs in cases) {
  case_qmd <- file.path(dir_cases, paste0("case-", cs$n2, ".qmd"))
  soln_rel <- file.path("..", "solutions", paste0("solution-", cs$n2, ".qmd"))
  write_utf8(c(
    "---",
    paste0("title: \"", cs$n2, " \u00b7 ", cs$title, "\""),
    "---",
    "",
    paste0(GENERATED_NOTE),
    "::: {.case-meta}",
    badge_line(cs),
    "",
    tag_line(cs),
    ":::",
    "",
    cs$case_body,
    "",
    "------------------------------------------------------------------------",
    "",
    paste0("[**\u2192 Reveal the solution**](", soln_rel, "){.solution-link}"),
    ""
  ), case_qmd)

  soln_qmd <- file.path(dir_solns, paste0("solution-", cs$n2, ".qmd"))
  case_rel <- file.path("..", "cases", paste0("case-", cs$n2, ".qmd"))
  write_utf8(c(
    "---",
    paste0("title: \"", cs$n2, " \u00b7 ", cs$title, " \u2014 Solution\""),
    "---",
    "",
    paste0(GENERATED_NOTE),
    paste0("[\u2190 Back to the case](", case_rel, "){.back-link}"),
    "",
    tag_line(cs),
    "",
    "------------------------------------------------------------------------",
    "",
    cs$soln_body,
    ""
  ), soln_qmd)
}

# ---- overview table ---------------------------------------------------------

ov <- c(
  "---", "title: \"The Cases\"", "---", "",
  GENERATED_NOTE,
  "Six crimes against causality await. Each one is a real-looking study, chart,",
  "or algorithm with a fatal flaw buried inside it. Read the crime scene, work",
  "through the interrogation, and form your own verdict before you reveal the",
  "solution.",
  "",
  "Cases are investigated by one of two detectives \u2014 see [The Detectives](../intro/detectives.qmd).",
  "Difficulty runs from \u25cf (Easy) to \u25cf\u25cf\u25cf (Hard).",
  "",
  "| # | Case | Detective | Difficulty | Topics | Fallacies |",
  "|---|------|-----------|:----------:|--------|-----------|"
)
for (cs in cases) {
  link <- paste0("[**", cs$title, "**](case-", cs$n2, ".qmd)<br><span class='case-blurb'>",
                 cs$summary, "</span>")
  ov <- c(ov, paste(
    "|", cs$n2,
    "|", link,
    "|", cs$detective,
    "|", paste0(difficulty_dots(cs$difficulty), "<br>", difficulty_label(cs$difficulty)),
    "|", paste(cs$topics, collapse = ", "),
    "|", paste(cs$fallacies, collapse = ", "), "|"))
}
write_utf8(ov, file.path(dir_cases, "overview.qmd"))

# ---- solutions landing page -------------------------------------------------

write_utf8(c(
  "---", "title: \"The Solutions\"", "---", "",
  GENERATED_NOTE,
  "Spoilers ahead. Each solution lays out the answers to the interrogation,",
  "explains what went wrong, gives the background, and points to further",
  "reading. Every solution links back to its case.",
  "",
  paste0("Jump to: ",
    paste(vapply(cases, function(cs)
      paste0("[", cs$n2, "](solution-", cs$n2, ".qmd)"), character(1)),
      collapse = " \u00b7 "))
), file.path(dir_solns, "index.qmd"))

# ---- aggregated bibliography ------------------------------------------------

collect_sources <- function(cs) {
  b <- cs$soln_body
  h <- heading_matching(b, "^sources?\\b|^further reading\\b|^references?\\b")
  if (length(h) == 0) return(character(0))
  start <- h[1] + 1
  nxt <- which(str_detect(b, "^#{1,6}\\s"))
  nxt <- nxt[nxt > h[1]]
  end <- if (length(nxt)) nxt[1] - 1 else length(b)
  src <- b[start:end]
  src <- src[str_detect(src, "^\\s*-\\s")]
  str_trim(str_replace(src, "^\\s*-\\s*", ""))
}
all_src <- unique(unlist(lapply(cases, collect_sources)))
all_src <- all_src[nzchar(all_src)]
all_src <- all_src[order(tolower(all_src))]
write_utf8(c(
  "---", "title: \"References & Further Reading\"", "---", "",
  GENERATED_NOTE,
  "Sources cited across all cases, collected here for convenience. Each case",
  "also lists its own sources at the end of its solution.",
  "",
  if (length(all_src)) paste0("- ", all_src) else "_No sources found._"
), file.path(book_dir, "references.qmd"))

# ---- tag index --------------------------------------------------------------

build_index_block <- function(field, label) {
  tagmap <- list()
  for (cs in cases) {
    for (t in cs[[field]]) {
      tagmap[[t]] <- c(tagmap[[t]], cs$n2)
    }
  }
  if (length(tagmap) == 0) return(character(0))
  out <- paste0("## ", label, "\n")
  for (t in sort(names(tagmap))) {
    ns <- tagmap[[t]]
    links <- vapply(ns, function(n)
      paste0("[", n, "](cases/case-", n, ".qmd)"), character(1))
    out <- c(out, paste0("**", t, "** \u2014 ", paste(links, collapse = ", "), "\n"))
  }
  c(out, "")
}
idx <- c(
  "---", "title: \"Index\"", "---", "",
  GENERATED_NOTE,
  "Find cases by what they are about and by the kind of reasoning error they",
  "expose.",
  "",
  build_index_block("topics", "By topic"),
  build_index_block("fallacies", "By fallacy"),
  build_index_block_difficulty <- {
    tagmap <- list()
    for (cs in cases) {
      lbl <- difficulty_label(cs$difficulty)
      tagmap[[lbl]] <- c(tagmap[[lbl]], cs$n2)
    }
    out <- "## By difficulty\n"
    for (lbl in c("Easy", "Medium", "Hard")) {
      if (is.null(tagmap[[lbl]])) next
      links <- vapply(tagmap[[lbl]], function(n)
        paste0("[", n, "](cases/case-", n, ".qmd)"), character(1))
      out <- c(out, paste0("**", lbl, "** \u2014 ", paste(links, collapse = ", "), "\n"))
    }
    out
  }
)
write_utf8(idx, file.path(book_dir, "appendix-index.qmd"))

# ---- intro pages from case-studies/*.md -------------------------------------

transform_simple_md <- function(src, dest, title, drop_from = NULL) {
  if (!file.exists(src)) {
    warning("Source not found, skipping: ", src); return(invisible())
  }
  lines <- readLines(src, warn = FALSE, encoding = "UTF-8")
  first_h1 <- which(str_detect(lines, "^#\\s"))[1]
  if (!is.na(first_h1)) lines <- lines[-(1:first_h1)]
  if (!is.null(drop_from)) {
    d <- heading_matching(lines, drop_from)
    if (length(d)) lines <- lines[seq_len(d[1] - 1)]
  }
  lines <- tidy_headings(lines)
  write_utf8(c("---", paste0("title: \"", title, "\""), "---", "",
               GENERATED_NOTE, lines), dest)
}
transform_simple_md(file.path(cases_src, "detectives.md"),
                    file.path(dir_intro, "detectives.qmd"),
                    "The Detectives", drop_from = "^case assignments")
transform_simple_md(file.path(cases_src, "lore.md"),
                    file.path(dir_intro, "world.qmd"),
                    "The World of Harland")

# ---- _quarto.yml ------------------------------------------------------------

yml <- c(
  "# DO NOT EDIT. Generated by scripts/build-book.R.",
  "# Edit scripts/build-book.R (the BOOK list) to change book-level settings.",
  "project:",
  "  type: book",
  "  output-dir: _book",
  "",
  "book:",
  paste0("  title: \"", BOOK$title, "\""),
  paste0("  subtitle: \"", BOOK$subtitle, "\""),
  "  author:",
  paste0("    - \"", BOOK$authors, "\""),
  paste0("  site-url: \"", BOOK$site_url, "\""),
  paste0("  repo-url: \"", BOOK$repo_url, "\""),
  "  search: true",
  "  page-navigation: true",
  "  chapters:",
  "    - index.qmd",
  "    - part: \"Introduction\"",
  "      chapters:",
  "        - intro/how-to-read.qmd",
  "        - intro/world.qmd",
  "        - intro/detectives.qmd",
  "    - part: \"The Cases\"",
  "      chapters:",
  "        - cases/overview.qmd"
)
yml <- c(yml, vapply(cases, function(cs)
  paste0("        - cases/case-", cs$n2, ".qmd"), character(1)))
yml <- c(yml,
  "    - part: \"The Solutions\"",
  "      chapters:",
  "        - solutions/index.qmd")
yml <- c(yml, vapply(cases, function(cs)
  paste0("        - solutions/solution-", cs$n2, ".qmd"), character(1)))
yml <- c(yml,
  "  appendices:",
  "    - references.qmd",
  "    - appendix-index.qmd",
  "",
  "format:",
  "  html:",
  "    theme:",
  "      - cosmo",
  "      - theme.scss",
  "    toc: true",
  "    number-depth: 1",
  "    fig-cap-location: top",
  "")
write_utf8(yml, file.path(book_dir, "_quarto.yml"))

message("Done. Wrote book/ for ", length(cases), " case(s).")
message("Render with:  quarto render book   (or: make preview)")
